[package]
name = "rs-jong"
version = "0.1.0"
authors = ["Lenqth <nullptr00@gmail.com>"]

[dependencies]
lazy_static = "1.4.0"
rand = "*"

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "*"
petgraph = "0.5.1"
