[package]
authors = ["Lenqth <nullptr00@gmail.com>"]
edition = "2018"
name = "cle"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"rs-jong" = {path = "../rs-jong"}
